#!/usr/bin/env python3
"""Verify a patches.instruction candidate lands on the right 4 ROM bytes BEFORE
recompiling. Subcommands: verify (default — read-only), preview (in-memory
diff), apply (writes the ROM irreversibly — back it up first).

WHY: separates "did I pick the right instruction?" from "did the recomp pick
it up?" — a `verify` mismatch means the recomp `// 0x8005FA3C: <wrong>` comment
should have been the tell, before wasting a full build.
"""
import struct
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
ROM = REPO / "Automobili Lamborghini (USA).z64"

# Issue #4 candidate — bc1f +0xDC at runtime 0x8005FA3C (rom offset 0x6063c).
# Layout at runtime 0x8005FA34 (big-endian):
#   0x8005FA34  0x4608003C  c.lt.s f0, f8   (sets CC0 — keep)
#   0x8005FA38  0x00000000  nop              (delay slot — keep)
#   0x8005FA3C  0x450000DC  bc1f +0xDC       <-- this becomes 0x00000000
#   0x8005FA40  0x00000000  nop              (delay slot — now real delay slot of the NOP)
CANDIDATE_VRAM = 0x8005FA3C
CANDIDATE_FUNC = "func_80060464"
EXPECTED_PRE_PATCH = 0x450000DC  # bc1f +0xDC
NEW_VALUE = 0x00000000            # MIPS canonical NOP

def vram_to_rom(vram):
    return vram - 0x7FFFF400

def read_rom_bytes(path, vram, count_words=4):
    """Read count_words MIPS instructions at the given runtime VRAM."""
    rom_offset = vram_to_rom(vram)
    out = []
    with path.open("rb") as f:
        f.seek(rom_offset)
        for _ in range(count_words):
            data = f.read(4)
            if len(data) < 4:
                raise EOFError(f"ROM ended at offset {rom_offset:#x}")
            out.append(struct.unpack(">I", data)[0])
    return out

def write_rom_word(path, vram, value):
    """Overwrite the 4-byte MIPS instruction at the given runtime VRAM."""
    rom_offset = vram_to_rom(vram)
    with path.open("r+b") as f:
        f.seek(rom_offset)
        f.write(struct.pack(">I", value))

def main():
    if not ROM.exists():
        print(f"ROM not found at {ROM}", file=sys.stderr)
        return 1

    cmd = sys.argv[1] if len(sys.argv) > 1 else "verify"
    if cmd not in ("verify", "preview", "apply"):
        print(f"usage: {sys.argv[0]} [verify|preview|apply]", file=sys.stderr)
        return 2

    print(f"ROM: {ROM}")
    print(f"Candidate VRAM: {CANDIDATE_VRAM:#010x}")
    print(f"Candidate function: {CANDIDATE_FUNC}")
    print()

    # Show the 4 instructions starting at the candidate VRAM
    words = read_rom_bytes(ROM, CANDIDATE_VRAM - 8, count_words=4)
    base = CANDIDATE_VRAM - 8
    print(f"Context (4 instructions around the candidate):")
    for i, w in enumerate(words):
        v = base + i * 4
        marker = ""
        if v == CANDIDATE_VRAM:
            marker = " <-- TARGET (patch to 0x00000000)"
        elif v == CANDIDATE_VRAM - 8:
            marker = "    (preceding: c.lt.s — sets FP condition flag CC0)"
        elif v == CANDIDATE_VRAM - 4:
            marker = "    (delay slot of c.lt.s — harmless nop)"
        elif v == CANDIDATE_VRAM + 4:
            marker = "    (delay slot of bc1f — now becomes real delay slot of NOP)"
        print(f"  {v:#010x}  {w:#010x}{marker}")
    print()

    target = words[2]  # the candidate VRAM is at index 2 (after -8, -4, candidate, +4)
    if target != EXPECTED_PRE_PATCH:
        print(f"WARNING: target byte at {CANDIDATE_VRAM:#010x} is {target:#010x},")
        print(f"expected {EXPECTED_PRE_PATCH:#010x} (bc1f +0xDC). The candidate may be wrong,")
        print(f"or the ROM version may differ. STOP and investigate before patching.")
        if cmd == "apply":
            print("Apply aborted.")
            return 3
    else:
        print(f"Target byte matches expected bc1f +0xDC: OK")
    print()

    if cmd == "verify":
        print("Verify mode: ROM unchanged.")
    elif cmd == "preview":
        print("Preview mode: ROM unchanged.")
        print(f"  If patched, {CANDIDATE_VRAM:#010x} would change: "
              f"{target:#010x} -> {NEW_VALUE:#010x}")
        print(f"  C source generated by N64Recomp would emit '// PATCHED' at this site")
        print(f"  and the recompiled function would no longer branch to the low-poly code.")
    elif cmd == "apply":
        print(f"APPLY MODE: about to write {NEW_VALUE:#010x} at ROM offset "
              f"{vram_to_rom(CANDIDATE_VRAM):#x}.")
        print(f"This is IRREVERSIBLE without a ROM backup. Press Enter to continue, "
              f"Ctrl-C to abort.")
        try:
            input()
        except KeyboardInterrupt:
            print("Aborted.")
            return 0
        write_rom_word(ROM, CANDIDATE_VRAM, NEW_VALUE)
        after = read_rom_bytes(ROM, CANDIDATE_VRAM, count_words=1)[0]
        print(f"Write complete. ROM now reads {after:#010x} at {CANDIDATE_VRAM:#010x}.")
        print("Next steps:")
        print("  1. cmake --build build --target N64RecompCLI")
        print("  2. ./build/lib/N64ModernRuntime/librecomp/N64Recomp/N64Recomp lamborghini.us.toml")
        print("  3. cmake --build build --target lamborghini_modern")
        print("  4. Boot, drive toward another car, watch for geometry pop.")

    return 0

if __name__ == "__main__":
    sys.exit(main())