// Implementation of the native crash backtrace (issue #13 / A14).
// See lambo_crash.h for the contract; comments in this file explain
// the trade-offs and the platform specifics.

#include "lambo_crash.h"

#include <algorithm>
#include <atomic>
#include <chrono>
#include <cstdio>
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <mutex>
#include <sstream>
#include <string>
#include <thread>
#include <unordered_map>
#include <vector>

#include "librecomp/sections.h"
#include "recomp.h"

#if defined(_WIN32)
    #define LAMBO_CRASH_WIN32 1
    #include <windows.h>
    #include <dbghelp.h>
    #include <malloc.h>      // _resetstkoflw
    #pragma comment(lib, "dbghelp.lib")
#else
    #define LAMBO_CRASH_POSIX 1
    #include <csignal>
    #include <execinfo.h>
    #include <unistd.h>
#endif

// ---------------------------------------------------------------------------
// Symbol table (parsed from lamborghini.syms.toml at install time).
// ---------------------------------------------------------------------------
namespace lambo::crash {

namespace {

// Pool of symbol name strings -- stored once, referenced by SymbolInfo[].
// lsrmr means we keep the lifetime simple (no per-symbol string heap churn).
struct SymbolPool {
    std::vector<std::string>       names;          // each holds a stable char* from .data()
    std::vector<SymbolInfo>        table;          // sorted by vram (binary-search lookup)
} g_pool;

const SymbolInfo* lookup_in_pool(uint32_t vram, uint32_t* out_offset_bytes) {
    if (g_pool.table.empty()) return nullptr;
    // Find the last entry whose vram <= query. upper_bound on vram, step one back.
    auto lo = g_pool.table.begin();
    auto hi = g_pool.table.end();
    auto it = std::upper_bound(lo, hi, vram, [](uint32_t val, const SymbolInfo& s) {
        return val < s.vram;
    });
    if (it == lo) {
        // vram is below the lowest symbol (could be before 0x80000400).
        if (out_offset_bytes) *out_offset_bytes = vram;
        return nullptr;
    }
    --it;
    if (vram - it->vram < it->size) {
        if (out_offset_bytes) *out_offset_bytes = vram - it->vram;
        return &*it;
    }
    // vram is in a hole between two functions, or past the last symbol.
    // Returning the lower-bound symbol + a too-large offset would
    // mis-attribute the PC. Report nullptr instead so the dump shows
    // raw "(no symbol)" plus the vram itself.
    return nullptr;
}

// Parse the relevant subset of lamborghini.syms.toml: the
// [[section]]/functions = [ ... ] table. Format is exactly:
//     { name = "BootMain", vram = 0x80000450, size = 0x68 },
// generated by scripts/gen_syms_toml.py and committed. The scanner is
// intentionally not a general TOML parser -- the format is fixed and
// trusting the generator's output lets us avoid pulling in toml++.
//
// Trace state: scanning goes through three nested forms:
//   [[section]]      -- section table starts. Ignored except to find the
//                       .text section's functions array.
//   functions = [ ... ] array -- the only form we extract from.
// Inside the functions array, each entry is a single inline-table on
// one line, terminated by `,` or `}`. The array itself ends at `]`.
bool load_symbol_table(const std::filesystem::path& syms_path) {
    std::ifstream f(syms_path);
    if (!f.good()) {
        std::fprintf(stderr, "[crash] syms file %s not found; dumps will show raw N64 PCs only\n",
                     syms_path.string().c_str());
        return false;
    }

    auto trim = [](std::string& s) {
        auto issp = [](unsigned char c) { return c == ' ' || c == '\t' || c == '\r' || c == '\n'; };
        size_t a = 0; while (a < s.size() && issp(s[a])) a++;
        size_t b = s.size(); while (b > a && issp(s[b - 1])) b--;
        s = s.substr(a, b - a);
    };

    g_pool.names.clear();
    g_pool.table.clear();
    // Pre-count entries so we can reserve capacity once -- the table
    // stores raw char* into the names vector, so any reallocation would
    // invalidate those pointers. The extra pass costs ~50ms on this
    // file's 1k-line payload; with reserve() we make exactly one pass
    // over the entries.
    size_t reserve_n = 0;
    {
        std::ifstream fc(syms_path);  // OK to share; std::ifstream is read-only.
        std::string lc;
        bool in_fn = false;
        while (std::getline(fc, lc)) {
            // Trim by hand (trim lambda isn't in scope here yet).
            auto issp = [](unsigned char c) { return c == ' ' || c == '\t' || c == '\r' || c == '\n'; };
            size_t a = 0; while (a < lc.size() && issp(lc[a])) a++;
            size_t b = lc.size(); while (b > a && issp(lc[b - 1])) b--;
            lc = lc.substr(a, b - a);
            if (lc.empty() || lc[0] == '#') continue;
            if (!in_fn) {
                if (lc.find("functions") != std::string::npos &&
                    lc.find('[') != std::string::npos) in_fn = true;
                continue;
            }
            if (lc.find(']') != std::string::npos) { in_fn = false; continue; }
            if (lc.find("name") != std::string::npos &&
                lc.find("vram") != std::string::npos) {
                reserve_n++;
            }
        }
    }
    g_pool.names.reserve(reserve_n);
    g_pool.table.reserve(reserve_n);

    // Single-pass: stream the file, when we see "functions = [" enter the
    // array body, parse each line that has both `name` and `vram`, exit
    // when we see a `]` line. Lines like the section header
    // `[[section]]` or `name = ".text"` are ignored.
    std::string line;
    bool in_functions = false;
    while (std::getline(f, line)) {
        trim(line);
        if (line.empty() || line[0] == '#') continue;
        if (!in_functions) {
            // The functions array begins on a line that mentions
            // 'functions' AND contains '['. lamborghini.syms.toml has
            // this on `functions = [`. We don't `continue` here -- if
            // we just crossed into the array body, we still want the
            // NEXT iteration to parse the first entry.
            if (line.find("functions") != std::string::npos &&
                line.find('[') != std::string::npos) {
                in_functions = true;
            }
            continue;
        }
        // Inside functions array. A `]` (with nothing else of note)
        // closes it.
        if (line.find(']') != std::string::npos) {
            in_functions = false;
            continue;
        }
        // Pick out name = "...", vram = 0xN, size = 0xN. Single-line
        // inline tables like `{ name = "X", vram = 0xY, size = 0xZ },`
        // are the only entry shape in this file. The skipper below also
        // walks past the inline-table delimiters `{` and `}` so each
        // key=value starts at the first non-token byte.
        std::string name; uint32_t vram = 0; uint32_t size = 0;
        size_t i = 0;
        bool got_all = true;
        while (i < line.size()) {
            while (i < line.size() && (line[i] == ' ' || line[i] == ',' || line[i] == '\t' ||
                                       line[i] == '{' || line[i] == '}')) i++;
            if (i >= line.size()) break;
            size_t eq = line.find('=', i);
            if (eq == std::string::npos) break;
            std::string key = line.substr(i, eq - i);
            trim(key);
            i = eq + 1;
            while (i < line.size() && (line[i] == ' ' || line[i] == '\t')) i++;
            if (i >= line.size()) { got_all = false; break; }
            if (line[i] == '"') {
                size_t end = line.find('"', i + 1);
                if (end == std::string::npos) { got_all = false; break; }
                std::string val = line.substr(i + 1, end - (i + 1));
                if (key == "name") name = val;
                i = end + 1;
            } else {
                size_t end = i;
                while (end < line.size() && line[end] != ',' && line[end] != ' ' &&
                       line[end] != '\t' && line[end] != '}') end++;
                std::string val = line.substr(i, end - i);
                trim(val);
                if (val.empty()) { got_all = false; break; }
                // Wrap the parse in try/catch -- std::stoul throws on
                // non-numeric input or overflow (e.g. "0x" with a missing
                // digit, or a future format change). Letting the exception
                // escape would abort startup before our handler is
                // installed; we want graceful degradation instead.
                try {
                    if (key == "vram") {
                        vram = (uint32_t)std::stoul(val, nullptr, 16);
                    } else if (key == "size") {
                        size = (uint32_t)std::stoul(val, nullptr, 16);
                    }
                } catch (std::exception const&) {
                    got_all = false;
                    break;
                }
                i = end;
            }
        }
        if (!name.empty() && got_all && vram != 0) {
            g_pool.names.emplace_back(std::move(name));
            const std::string& nb = g_pool.names.back();
            g_pool.table.push_back({ nb.c_str(), vram, size });
        }
    }

    // stable_sort: lamborghini.syms.toml can contain multiple symbols at
    // the SAME vram (e.g. func_80008290 and func_80008E90 both at
    // 0x80007690 -- aliases generated by the race-split merger). std::sort
    // would let those swing between runs; stable_sort preserves source
    // order so the attributed name is identical run-to-run (the
    // difference matters for crash-digest CI runs).
    std::stable_sort(g_pool.table.begin(), g_pool.table.end(),
              [](const SymbolInfo& a, const SymbolInfo& b) { return a.vram < b.vram; });
    std::fprintf(stderr, "[crash] loaded %zu symbols from %s\n",
                 g_pool.table.size(), syms_path.string().c_str());
    return !g_pool.table.empty();
}

void find_and_load_symbol_table() {
    // Candidate order: env override > cwd > exe/.. > exe. The syms file
    // is committed next to the binary in the typical dev workflow, but
    // a Steam Deck install won't have it -- the env override lets ops
    // point at a 'symbols.zip' alongside the build.
    const char* env = std::getenv("LAMBO_CRASH_SYMBOLS");
    std::vector<std::filesystem::path> candidates;
    if (env && env[0] != '\0') candidates.emplace_back(env);
    candidates.emplace_back(std::filesystem::current_path() / "lamborghini.syms.toml");
#if defined(_WIN32)
    {
        char exe_buf[MAX_PATH];
        DWORD n = GetModuleFileNameA(nullptr, exe_buf, MAX_PATH);
        if (n > 0 && n < MAX_PATH) {
            std::filesystem::path exedir = std::filesystem::path(std::string(exe_buf, n)).parent_path();
            candidates.emplace_back(exedir / "lamborghini.syms.toml");
            candidates.emplace_back(exedir.parent_path() / "lamborghini.syms.toml");
        }
    }
#else
    {
        std::filesystem::path self = std::filesystem::read_symlink("/proc/self/exe");
        candidates.emplace_back(self.parent_path() / "lamborghini.syms.toml");
        candidates.emplace_back(self.parent_path().parent_path() / "lamborghini.syms.toml");
    }
#endif
    for (const auto& p : candidates) {
        if (load_symbol_table(p)) return;
    }
}

} // namespace

const SymbolInfo* lookup(uint32_t vram, uint32_t* out_offset_bytes) {
    return lookup_in_pool(vram, out_offset_bytes);
}

// ---------------------------------------------------------------------------
// C-func pointer -> N64 vram map. The recomp_overlays data is exposed by
// register_overlays.cpp; we re-import the section_table here to populate
// this map at install time. (Avoids a second extern decl in the harness --
// the same declarations live in register_overlays.cpp.)
// ---------------------------------------------------------------------------
namespace {

std::unordered_map<const void*, uint32_t> g_native_to_vram;

} // namespace

// Called by register_overlays.cpp after the section tables it includes
// from recomp_overlays.inl have been registered with librecomp. We could
// recompute the map by reading `recomp::overlays::get_section_addresses()`
// at runtime, but the simpler path is for the only TU that already has
// the section_table extern to also export it here.
extern "C" void lambo_crash_register_code_ptrs(
    uint32_t ram_addr, uint32_t /*size*/, FuncEntry* funcs, size_t num_funcs) {
    for (size_t k = 0; k < num_funcs; k++) {
        uint32_t vram = ram_addr + funcs[k].offset;
        g_native_to_vram.emplace((const void*)funcs[k].func, vram);
    }
}

// ---------------------------------------------------------------------------
// Trace ring (issue #13: "32-entry function-lookup trace ring").
// ---------------------------------------------------------------------------
namespace {

constexpr uint32_t kRingSize = 32;
struct RingEntry {
    uint32_t vram;        // N64 PC of the function we just entered
    uint32_t ra_vram;     // N64 $ra at that point (return address)
    uint64_t tsc_us;      // monotonic microseconds since install
    std::thread::id tid;  // thread that pushed it
};

RingEntry       g_ring[kRingSize] = {};
uint32_t        g_ring_cursor = 0;       // next slot to write; wraps modulo kRingSize
std::mutex      g_ring_lock;              // serialises the (rare) push + cursor inc
uint64_t        g_tsc_base_us = 0;        // captured at first push (under the lock)

uint64_t now_us() {
    using namespace std::chrono;
    return duration_cast<microseconds>(steady_clock::now().time_since_epoch()).count();
}

} // namespace

void record_recent(uint32_t vram, uint32_t ra_vram) {
    std::lock_guard<std::mutex> lk(g_ring_lock);
    if (g_tsc_base_us == 0) g_tsc_base_us = now_us();
    uint32_t i = g_ring_cursor++ % kRingSize;
    g_ring[i] = { vram, ra_vram, now_us() - g_tsc_base_us, std::this_thread::get_id() };
}

namespace {

void print_ring_impl(FILE* fp, const char* header) {
    // The crash thread may already be holding g_ring_lock (e.g. a SIGSEGV
    // landing mid- record_recent). A non-recursive std::mutex would
    // deadlock the signal-handler-from-same-thread case -- the very bug
    // the dump is meant to diagnose. try_lock degrades to "(ring locked;
    // skipping)".
    if (!g_ring_lock.try_lock()) {
        std::fprintf(fp, "%s (skipped: ring lock held by crashing thread)\n", header);
        return;
    }
    std::lock_guard<std::mutex> lk(g_ring_lock, std::adopt_lock);
    uint32_t cur = g_ring_cursor;
    std::fprintf(fp, "%s (most recent first, %u entries max):\n", header, kRingSize);
    // 'cur' is the next slot to write -- the OLDEST entry. Walk BACKWARDS
    // so the dump's [0] is the most recent push, like a stack trace.
    for (uint32_t off = 0; off < kRingSize; off++) {
        uint32_t idx = (cur + kRingSize - 1 - off) % kRingSize;
        const RingEntry& e = g_ring[idx];
        if (e.tsc_us == 0 && e.vram == 0 && e.ra_vram == 0) continue; // empty slot
        uint32_t offb = 0;
        const SymbolInfo* si = lookup_in_pool(e.vram, &offb);
        char vname[160];
        if (si) {
            std::snprintf(vname, sizeof(vname), "%s+0x%X", si->name, offb);
        } else {
            std::snprintf(vname, sizeof(vname), "0x%08X", e.vram);
        }
        std::fprintf(fp, "  [%2u] t=%llu.%03llums vram=%s ra=0x%08X tid=%zu\n",
                     off,
                     (unsigned long long)(e.tsc_us / 1000),
                     (unsigned long long)(e.tsc_us % 1000),
                     vname,
                     e.ra_vram,
                     std::hash<std::thread::id>{}(e.tid));
    }
}

} // namespace

// ---------------------------------------------------------------------------
// KSEG0 / RDRAM address translation.
// ---------------------------------------------------------------------------
//
// N64 has four canonical physical-to-virtual mappings:
//   00000000-1FFFFFFF : kuseg  (TLB-translated; user)
//   80000000-9FFFFFFF : kseg0  (cached, direct-mapped; RDRAM + 0x80000000)
//   A0000000-BFFFFFFF : kseg1  (uncached, direct-mapped; RDRAM + 0xA0000000)
//   C0000000-FFFFEFFF : kseg2  (TLB-translated; kernel)
// On hardware the upper 3 bits select the segment; the offset within
// RAM is the low 29 bits for kseg0/kseg1. Our recomp runtime stores
// RDRAM at the LO half of the recomp's gpr address space:
//   rdram + (reg - 0xFFFFFFFF80000000UL)        (= rdram + (reg + 0x80000000))
// which means: rdram_offset_for_vram(v) = v & 0x1FFFFFFF for any
// segment where the low 29 bits are the real RDRAM byte offset.

constexpr uint32_t kRdramBase   = 0x80000000u;
constexpr uint32_t kRdramMask   = 0x1FFFFFFFu;       // low 29 bits = byte offset

bool rdram_offset_for_vram(uint32_t vram, uint32_t& off_out) {
    uint32_t hi = vram & 0xE0000000u;
    if (hi == kRdramBase || hi == 0xA0000000u) {
        off_out = vram & kRdramMask;
        return true;
    }
    return false;
}

void print_vram_translation(FILE* fp, uint32_t vram) {
    uint32_t off = 0;
    if (rdram_offset_for_vram(vram, off)) {
        std::fprintf(fp, "  vram 0x%08X -> RDRAM offset 0x%07X (kseg0 0x%08X / kseg1 0x%08X)\n",
                     vram, off, kRdramBase + off, 0xA0000000u + off);
    } else {
        std::fprintf(fp, "  vram 0x%08X (segment not RDRAM-direct; not addressable by recomp)\n", vram);
    }
}

// ---------------------------------------------------------------------------
// Native backtrace -> N64 vram translation.
// ---------------------------------------------------------------------------
namespace {

// Identify which recompiled function a native code pointer belongs to, by
// matching it against the FuncEntry.func map we built from section_table.
// Returns 0 if the address is outside any recomp body.
//
// Sanity-guarded: the "highest base <= pc" fallback is a noisy guess.
// A real PC inside a recompiled function is within a few KB of its
// FuncEntry.func; anything hundreds of KB away is almost certainly a
// Windows system DLL or libc and should NOT be misattributed. The 64 KiB
// ceiling is roughly the 95-percentile recomp-func body size on this
// port; we err on the generous side.
uint32_t native_pc_to_vram(const void* pc) {
    if (g_native_to_vram.empty()) return 0;
    constexpr uintptr_t kMaxDistance = 64 * 1024;
    auto it = g_native_to_vram.find(pc);
    if (it != g_native_to_vram.end()) return it->second;

    const void* best = nullptr; uint32_t best_v = 0;
    for (const auto& kv : g_native_to_vram) {
        if (kv.first <= pc) {
            uintptr_t dist = (uintptr_t)pc - (uintptr_t)kv.first;
            if (dist > kMaxDistance) continue;
            if (best == nullptr || kv.first > best) {
                best = kv.first; best_v = kv.second;
            }
        }
    }
    return best_v;
}

} // namespace

// ---------------------------------------------------------------------------
// Crash handlers (Win32 vectored exception handler / POSIX sigaction).
// ---------------------------------------------------------------------------
namespace {

const char* win32_exception_name(DWORD code) {
    switch (code) {
        case EXCEPTION_ACCESS_VIOLATION:  return "EXCEPTION_ACCESS_VIOLATION";
        case EXCEPTION_INT_DIVIDE_BY_ZERO:return "EXCEPTION_INT_DIVIDE_BY_ZERO";
        case EXCEPTION_STACK_OVERFLOW:    return "EXCEPTION_STACK_OVERFLOW";
        case EXCEPTION_ILLEGAL_INSTRUCTION: return "EXCEPTION_ILLEGAL_INSTRUCTION";
        case EXCEPTION_PRIV_INSTRUCTION:  return "EXCEPTION_PRIV_INSTRUCTION";
        case EXCEPTION_BREAKPOINT:        return "EXCEPTION_BREAKPOINT";
        case EXCEPTION_SINGLE_STEP:       return "EXCEPTION_SINGLE_STEP";
        case EXCEPTION_ARRAY_BOUNDS_EXCEEDED: return "EXCEPTION_ARRAY_BOUNDS_EXCEEDED";
        case EXCEPTION_FLT_DENORMAL_OPERAND:  return "EXCEPTION_FLT_DENORMAL_OPERAND";
        case EXCEPTION_FLT_DIVIDE_BY_ZERO:    return "EXCEPTION_FLT_DIVIDE_BY_ZERO";
        case EXCEPTION_FLT_INEXACT_RESULT:    return "EXCEPTION_FLT_INEXACT_RESULT";
        case EXCEPTION_FLT_INVALID_OPERATION: return "EXCEPTION_FLT_INVALID_OPERATION";
        case EXCEPTION_FLT_OVERFLOW:          return "EXCEPTION_FLT_OVERFLOW";
        case EXCEPTION_FLT_STACK_CHECK:       return "EXCEPTION_FLT_STACK_CHECK";
        case EXCEPTION_FLT_UNDERFLOW:         return "EXCEPTION_FLT_UNDERFLOW";
        default:                              return "EXCEPTION_UNKNOWN";
    }
}

void print_native_backtrace(FILE* fp, const void* const* pcs, int n, const char* kind) {
    std::fprintf(fp, "  native backtrace (%s, %d frames):\n", kind, n);
    for (int i = 0; i < n; i++) {
        const void* pc = pcs[i];
        uint32_t vram = native_pc_to_vram(pc);
        char vbuf[160] = "";
        if (vram != 0) {
            uint32_t offb = 0;
            const SymbolInfo* si = lookup_in_pool(vram, &offb);
            if (si) std::snprintf(vbuf, sizeof(vbuf), "  --> n64 %s+0x%X",
                                  si->name, offb);
            else    std::snprintf(vbuf, sizeof(vbuf), "  --> n64 0x%08X", vram);
        }
        std::fprintf(fp, "    [%2d] native=%p%s\n", i, pc, vbuf);
    }
}

// Print the backtrace for a fatal signal. The whole point of this module
// is that the operator gets to see *something* the moment a SIGSEGV lands
// in the field, so writes funnel through a single stderr-emitting helper.
void dump_crash_state(const char* reason, uint32_t vram_guess) {
    FILE* fp = stderr;
    std::fprintf(fp, "\n========================= NATIVE CRASH =========================\n");
    if (reason) std::fprintf(fp, "Reason: %s\n", reason);

    if (vram_guess != 0) {
        uint32_t off = 0;
        std::fprintf(fp, "Guest PC at crash: 0x%08X", vram_guess);
        if (rdram_offset_for_vram(vram_guess, off)) {
            std::fprintf(fp, "  (RDRAM offset 0x%07X)\n", off);
        } else {
            std::fprintf(fp, "\n");
        }
        uint32_t offb = 0;
        if (const SymbolInfo* si = lookup_in_pool(vram_guess, &offb)) {
            std::fprintf(fp, "  function: %s+0x%X (size 0x%X)\n",
                         si->name, offb, si->size);
        }
    }

    print_ring_impl(fp, "Trace ring");
}

// Public exception-/signal-capture entry, called from BOTH the Win32
// handler and the POSIX handler, after they have gathered whatever
// platform-specific context they can (vram, native PCs).
void final_dump_and_die(const char* reason, uint32_t vram_guess,
                        const void* const* native_pcs, int native_pcs_n,
                        const char* kind) {
    FILE* fp = stderr;
    dump_crash_state(reason, vram_guess);
    if (native_pcs && native_pcs_n > 0) {
        print_native_backtrace(fp, native_pcs, native_pcs_n, kind);
    }
    std::fflush(fp);
    // Use _Exit (not abort) -- we *intentionally* finished our dump; do
    // not re-enter our handler via an abort-induced SIGABRT.
    std::_Exit(EXIT_FAILURE);
}

#if defined(LAMBO_CRASH_WIN32)

LONG WINAPI win32_vectored_handler(EXCEPTION_POINTERS* ep) {
    DWORD code = ep->ExceptionRecord->ExceptionCode;
    // Skip non-fatal breakpoint / single-step (those come from the
    // debugger). Fatal only.
    switch (code) {
        case EXCEPTION_BREAKPOINT:
        case EXCEPTION_SINGLE_STEP:
            return EXCEPTION_CONTINUE_SEARCH;
        default: break;
    }
    // STACK_OVERFLOW is special: the dump path itself uses printf,
    // which advances RSP back into the guard page that just faulted
    // and re-faults before any byte leaves the buffer. Call
    // _resetstkoflw to bump RSP past the guard, then proceed to dump;
    // the recomp body that recursed will not get a chance to recover
    // but at least the operator sees a partial dump.
    if (code == EXCEPTION_STACK_OVERFLOW) {
        _resetstkoflw();
        // ...but our own stack is still tiny. Fall through to a
        // minimal-banner variant of the dump, no native backtrace.
        std::fprintf(stderr,
                     "\n========================= NATIVE CRASH =========================\n"
                     "Reason: %s\n"
                     "(dump truncated: stack overflow -- no native backtrace recoverable)\n",
                     win32_exception_name(code));
        std::_Exit(EXIT_FAILURE);
    }
    // Pull the violation address when available (ACCESS_VIOLATION writes
    // it into ExceptionInformation[1]). We treat it as a KSEG0/KSEG1
    // guest address *only* if the low-32 bits look like a guest pointer
    // (typical MEM_W/MEM_H recomp derefs land here). Anything else is a
    // native host pointer -- a stack/heap wild pointer that won't
    // translate via the symbol table.
    uint32_t vram_guess = 0;
    if (code == EXCEPTION_ACCESS_VIOLATION &&
        ep->ExceptionRecord->NumberParameters >= 2) {
        auto addr = (uintptr_t)ep->ExceptionRecord->ExceptionInformation[1];
        uint32_t lo = (uint32_t)addr;
        uint32_t hi = lo & 0xE0000000u;
        if (hi == 0x80000000u || hi == 0xA0000000u) vram_guess = lo;
    }
    void* native_pcs[64];
    USHORT n = CaptureStackBackTrace(0, 64, (PVOID*)native_pcs, nullptr);
    final_dump_and_die(win32_exception_name(code), vram_guess,
                       (const void* const*)native_pcs, n, "Win32 CaptureStackBackTrace");
    // final_dump_and_die is [[noreturn]]; the line below is unreachable
    // and is the SEH-__except return value, NOT a vectored-handler return
    // (vectored handlers accept only CONTINUE_EXECUTION / CONTINUE_SEARCH).
    return EXCEPTION_CONTINUE_SEARCH;
}

#else // POSIX

void posix_signal_handler(int sig, siginfo_t* info, void* /*ucontext*/) {
    const char* reason = nullptr;
    switch (sig) {
        case SIGSEGV: reason = "SIGSEGV (segmentation fault)"; break;
        case SIGBUS:  reason = "SIGBUS (bus error)";          break;
        case SIGABRT: reason = "SIGABRT (assert/abort)";      break;
        case SIGFPE:  reason = "SIGFPE (floating-point/div0)"; break;
        case SIGILL:  reason = "SIGILL (illegal instruction)"; break;
        default:      reason = "<unknown signal>";             break;
    }
    // The si_addr field is the *guest* cause address when the SIGSEGV
    // came from MEM_W/MEM_H style macros; treat as vram *only* if it
    // parses as a KSEG0/KSEG1 address, otherwise it is a host pointer
    // we already covered via backtrace().
    uint32_t vram_guess = 0;
    if (sig == SIGSEGV && info && info->si_addr) {
        auto addr = (uintptr_t)info->si_addr;
        if (addr <= 0xFFFFFFFFu) {
            uint32_t v = (uint32_t)addr;
            uint32_t hi = v & 0xE0000000u;
            if (hi == 0x80000000u || hi == 0xA0000000u) vram_guess = v;
        }
    }
    void* native_pcs[64];
    int n = backtrace(native_pcs, 64);
    final_dump_and_die(reason, vram_guess,
                       (const void* const*)native_pcs, n, "POSIX backtrace(3)");
    std::_Exit(EXIT_FAILURE); // unreachable
}

void install_posix() {
    // Register an alternate signal stack so SIGSEGV from stack-overflow
    // (recursive recomp) doesn't deliver the handler on the same stack
    // that just ran out -- the handler's fprintf would then re-fault.
    // The stack is leaked on process exit, which is fine: the lifetime
    // is process-bound and the size is small (64 KiB).
    static char alt_stack_buf[SIGSTKSZ];
    static stack_t alt_stack{};
    alt_stack.ss_sp    = alt_stack_buf;
    alt_stack.ss_size  = sizeof(alt_stack_buf);
    alt_stack.ss_flags = 0;
    if (sigaltstack(&alt_stack, nullptr) != 0) {
        std::fprintf(stderr, "[crash] sigaltstack failed; stack-overflow dumps may not land\n");
    }

    struct sigaction sa{};
    sa.sa_sigaction = posix_signal_handler;
    // SA_ONSTACK so the alt stack above is used; SA_RESETHAND so a
    // second crash in the same process chains to the OS default
    // (avoid infinite-loop dumps after a fatal-on-fault); SA_SIGINFO so
    // we get si_addr etc. SIGABRT is NOT in the list because the
    // recomp runtime uses abort() via assert(false) in do_break /
    // switch_error -- those are controlled terminations and should
    // not be diagnosed as crashes.
    sa.sa_flags     = SA_SIGINFO | SA_RESETHAND | SA_ONSTACK;
    sigemptyset(&sa.sa_mask);
    int fatal[] = { SIGSEGV, SIGBUS, SIGFPE, SIGILL };
    for (int s : fatal) {
        if (sigaction(s, &sa, nullptr) != 0) {
            std::fprintf(stderr, "[crash] sigaction(%d) failed; crash dumps disabled for this signal\n", s);
        }
    }
}

#endif

} // namespace

void install() {
    static std::atomic<bool> once{false};
    bool expected = false;
    if (!once.compare_exchange_strong(expected, true)) return;
#if defined(LAMBO_CRASH_POSIX)
    // Install the POSIX signal handlers BEFORE the syms file IO: a stalled
    // anti-virus scanner reading the TOML or a real fault on another
    // thread while we're inside find_and_load_symbol_table() must still
    // reach a handler. The native->vram map is already populated by
    // register_overlays() earlier in main().
    install_posix();
#endif
    find_and_load_symbol_table();
#if defined(LAMBO_CRASH_WIN32)
    void* veh = AddVectoredExceptionHandler(0, win32_vectored_handler);
    if (veh == nullptr) {
        std::fprintf(stderr, "[crash] AddVectoredExceptionHandler returned NULL; dumps UNRELIABLE\n");
    }
#endif
    std::fprintf(stderr, "[crash] native crash handler installed (%s)\n",
#if defined(LAMBO_CRASH_WIN32)
                 "Win32 AddVectoredExceptionHandler"
#else
                 "POSIX sigaction (with sigaltstack)"
#endif
    );
}

[[noreturn]] void crash_dump_and_die(const char* reason) {
    // Walk the stack ourselves and emit the dump -- easier to validate the
    // output format than going through the OS signal path (BREAKPOINT/SIGABRT
    // may be filtered by gdb or the user's shell trap).
    void* native_pcs[64];
    int n = 0;
#if defined(LAMBO_CRASH_WIN32)
    n = (int)CaptureStackBackTrace(0, 64, (PVOID*)native_pcs, nullptr);
#else
    n = backtrace(native_pcs, 64);
#endif
    final_dump_and_die(reason ? reason : "deliberate crash",
                       0, (const void* const*)native_pcs, n,
#if defined(LAMBO_CRASH_WIN32)
                       "Win32 CaptureStackBackTrace (deliberate)");
#else
                       "POSIX backtrace(3) (deliberate)");
#endif
    // final_dump_and_die is [[noreturn]] via std::_Exit, but suppress the
    // "control reaches end of non-void function" warning just in case.
    std::_Exit(EXIT_FAILURE);
}

} // namespace lambo::crash
