// Headless boot probe for the ultramodern pivot (epic #54, phase #57).
//
// Links the whole-ROM recompiled image (RecompiledFuncs) against librecomp +
// ultramodern and boots the REAL entrypoint (0x80000400) under the modern
// runtime, with stubbed rsp/renderer callbacks and no RT64/SDL. Goal: confirm
// the recompiled boot reaches the first VI retrace and creates its first game
// thread (osCreateThread). A stall before that is a legitimate, characterised
// finding (run under gdb to capture the PC).
//
// Build/run (WSL): see recomp/CMakeLists.txt header.

#include <algorithm>
#include <atomic>
#include <chrono>
#include <cctype>
#include <cmath>
#include <condition_variable>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <filesystem>
#include <memory>
#include <mutex>
#include <string>
#include <thread>
#include <utility>
#include <vector>

#include "librecomp/game.hpp"
#include "librecomp/rsp.hpp"
#include "ultramodern/ultramodern.hpp"
#include "ultramodern/events.hpp"
#include "ultramodern/error_handling.hpp"
#include "ultramodern/renderer_context.hpp"
#include "ultramodern/input.hpp"

#include <limits>

#include <SDL.h>          // RT64 default presenter (#58): real window + event pump under WSLg
#if defined(_WIN32)
#include <SDL_syswm.h>    // native Windows (#68): unwrap the HWND for ultramodern/RT64-D3D12
#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <shellapi.h>
#endif
#include "lambo_rt64.h"
#include "lambo_audio.h"
#include "lambo_config.h"
#include "lambo_crash.h"   // issue #13 / A14
#include "lambo_gpu_advisory.h"  // issue #109: outdated-driver popup handoff
#include "lambo_log.h"   
#include "lambo_pak_io.h"
#include "lambo_pak_storage.h"
#include "lambo_menu.h"
#include "lambo_input_gate.h"
#include "lambo_analog_throttle.h"
#include "lambo_analog_brake.h"
#include "lambo_harness_report.h"
#include "lambo_replay_runtime.h"
#include "lambo_startup.h"
#include "controls/lambo_controls_sdl.h"
#include "ui/lambo_ui.h"
// ultramodern's native VI API (events.cpp), used by the promote_vi_context RT64 bridge.
extern "C" void osViSwapBuffer(uint8_t* rdram, int32_t frameBufPtr);
extern "C" void osViSetMode(uint8_t* rdram, int32_t mode_);

// Generated by N64Recomp (RecompiledFuncs/), the ROM-header entrypoint.
extern "C" void recomp_entrypoint(uint8_t* rdram, recomp_context* ctx);

// Our sibling TUs.
void register_overlays();
namespace headless {
std::unique_ptr<ultramodern::renderer::RendererContext>
create_render_context(uint8_t* rdram, ultramodern::renderer::WindowHandle window_handle, bool developer_mode);
int run_lighting_selftest();
}

static std::mutex g_termination_mutex;
static std::condition_variable g_termination_latch;
static bool g_termination_claimed = false;

// LAMBO_CRASH_TEST: when set, the test thread's 2 s sleep must outlast
// boot_summary_and_exit() so its deliberate crash fires. Disable the VI cap.
static int quit_after_vis() {
    if (const char* e = std::getenv("LAMBO_MODERN_MAX_VIS")) {
        int v = std::atoi(e);
        if (v > 0) return v;
    }
    if (std::getenv("LAMBO_CRASH_TEST")) return std::numeric_limits<int>::max();
    return lambo_rt64::enabled() ? std::numeric_limits<int>::max() : 120;
}
static const int kQuitAfterVis = quit_after_vis();

// Stall watchdog timeout. MUST exceed the wall-time the VI budget needs, or a raised
// LAMBO_MODERN_MAX_VIS is silently truncated by the watchdog before reaching the cap.
// Derive it from the cap (headless runs well above 10 VI/s, so cap/10 is generous) with
// a 30 s floor for the default boot. Uncapped play mode gets no watchdog (INT_MAX/10
// seconds is effectively never, and killing a live game window from a stall heuristic
// would be wrong anyway).
static int watchdog_seconds() {
    return std::max(30, kQuitAfterVis / 10 + 5);
}

static void on_init_cb(uint8_t*, recomp_context*) {
    LAMBO_LOG("probe", "init complete; entering recomp_entrypoint @ 0x80000400\n");
}

static void thread_create_cb(uint8_t*, recomp_context*) {
    lambo::harness::note_thread_created();
}

// Multiple native threads can request finalization; serialize the publisher.
static void claim_immediate_exit() {
    std::unique_lock lock(g_termination_mutex);
    if (!g_termination_claimed) {
        g_termination_claimed = true;
        return;
    }
    g_termination_latch.wait(lock, [] { return false; });
}

// Print the one-line boot summary the runtime guard (tests/pivot/test_boot_smoke.py) parses,
// then terminate the process immediately. We _Exit instead of returning through
// recomp::start()'s teardown on purpose: that teardown joins the helper threads and munmaps
// RDRAM, but it does NOT terminate the 7 game osCreateThread threads -- once the main game
// thread actually runs its per-frame dispatch loop, those threads are live in native
// osRecvMesg and race the munmap into a SIGSEGV. This is a headless boot/probe harness that is
// quitting anyway, so skip the unwind and let process exit tear the game threads down.
    // (Graceful game-thread shutdown is RT64-integration work, #58.)
[[noreturn]] static void boot_summary_and_exit() {
    claim_immediate_exit();
    lambo::harness::log_boot_summary();
    const lambo::harness::Snapshot metrics = lambo::harness::snapshot();
    const lambo::harness::Outcome outcome = lambo::harness::finalize_outcome(
        "max_vis", metrics.first_vi ? 0 : 2);
    lambo::harness::write_result(outcome);
    (void)lambo_pak_storage_flush();
    lambo_log_shutdown();
    std::fflush(nullptr);
    std::_Exit(outcome.exit_code);
}

[[noreturn]] static void harness_summary_and_exit(const char* reason, int exit_code) {
    claim_immediate_exit();
    const lambo::harness::Outcome outcome = lambo::harness::finalize_outcome(reason, exit_code);
    LAMBO_LOG("harness", "scenario finished; reason=%s status=%d\n",
              outcome.reason.c_str(), outcome.exit_code);
    lambo::harness::log_boot_summary();
    lambo::harness::write_result(outcome);
    (void)lambo_pak_storage_flush();
    lambo_log_shutdown();
    std::fflush(nullptr);
    std::_Exit(outcome.exit_code);
}

[[noreturn]] static void application_exit_success() {
    claim_immediate_exit();
    LAMBO_LOG("probe", "application exit requested; status=success\n");
    // update_gfx_stub runs on librecomp's primary thread, while RT64 invokes the
    // UI render hooks on its presentation thread. Calling ui::shutdown() here
    // races that thread: it clears RT64's unsynchronised hook pointers and tears
    // down RmlUi while a draw hook can still be using it. This path deliberately
    // terminates the process below, so there is no cleanup benefit that can
    // justify touching either subsystem first.
    const lambo::harness::Outcome outcome = lambo::harness::finalize_outcome("runtime_exit", 0);
    lambo::harness::write_result(outcome);
    (void)lambo_pak_storage_flush();
    lambo_log_shutdown();
    std::fflush(nullptr);
    if (outcome.exit_code == 0) std::_Exit(0);
    std::_Exit(outcome.exit_code);
}

// Set by headless::create_render_context (stub_renderer.cpp) so this retrace hook can reach RDRAM.
extern uint8_t* g_lambo_rdram;

// Emulate libultra's retrace-time __osViSwapContext for THIS game's osScheduler (#58).
//
// ultramodern reimplements the PUBLIC libultra VI API (osViSwapBuffer/osViGetCurrentFramebuffer)
// as natives, but this game's osScheduler reaches into the PRIVATE VI-manager state __osViCurr
// (0x8008D1A0) / __osViNext (0x8008D1A4) that only libultra's VI INTERRUPT used to maintain. Its
// gfx-task scheduling gate (__scTaskReady -> func_80074380) runs a task only when
//   __osViCurr->buffer (+0x4) == __osViNext->buffer (+0x4).
// On real hardware the VI retrace ISR's __osViSwapContext promotes __osViCurr <- __osViNext every
// frame, so once a requested swap is applied the two match again and the gate reopens. ultramodern
// replaced that ISR (and __osViInit is a no-op stub), so __osViCurr stayed frozen at 0 while
// __osViNext advanced to the pending framebuffer -> the gate latched shut after frame 1 and only the
// first gfx OSTask ever reached the renderer (the #58 1-task stall). Mirroring the buffer field each
// retrace reopens the gate with correct 1-frame-per-retrace pacing. This is faithful libultra VI
// behaviour, not a scaffold, so it is the default. (When RT64 lands this hook stays — it is the
// game's registered retrace callback.)
static void promote_vi_context() {
    uint8_t* rdram = g_lambo_rdram;
    if (rdram == nullptr) return;
    auto gw = [&](uint32_t a) -> uint32_t { return *(uint32_t*)(rdram + (a - 0x80000000u)); };
    auto sw = [&](uint32_t a, uint32_t v) { *(uint32_t*)(rdram + (a - 0x80000000u)) = v; };
    auto in_rdram = [](uint32_t a) { return a >= 0x80000000u && a < 0x80800000u; };
    uint32_t curr = gw(0x8008D1A0); // __osViCurr
    uint32_t next = gw(0x8008D1A4); // __osViNext
    if (!in_rdram(curr) || !in_rdram(next)) return;
    // Promote the WHOLE 0x30 context, not just the buffer field: ares RDRAM dumps show the two
    // OSViContexts byte-identical every frame (title dump 0x8008D140/0x8008D170), which is the
    // hardware __osViSwapContext's net effect. The buffer word (+0x4) is the scheduler gate;
    // modep (+0x8) and control (+0xC) are live since osViSetMode (func_80075C60) was un-stubbed
    // (W115: LPN2 0x8008C4A0 at boot, LAN2 0x8008C540 from the game SM -- matches ares).
    for (uint32_t off = 0; off < 0x30; off += 4) sw(curr + off, gw(next + off));
    // VI present-path bridge (#58, default since the 2026-07-02 RT64 flip): apply the game's
    // VI-manager state to ultramodern's VI natives at retrace cadence -- the exact values and
    // timing libultra's __osViSwapContext would have used. osViSetMode only on a modep
    // transition (the native reconfigures the display; hardware re-applies registers every
    // frame but the config is idempotent). Unconditional (also headless): ultramodern's VI
    // state simply goes unconsumed without a presenting renderer, and one code path keeps the
    // trunk stress-tested. NOTE events.cpp patch-0002's dummy-mode hunk is NOT retired with the
    // flip: W115 observed dummy-mode scanout live, i.e. VI ticks do land in the game-started ->
    // first-osViSetMode window while RT64/Vulkan init delays the first tick -- without the
    // hunk's mode==nullptr guard, update_vi() derefs null there. It is a null-guard for that
    // race, not a scaffold.
    {
        uint32_t modep = gw(next + 0x8);
        uint32_t buf   = gw(next + 0x4);
        static uint32_t s_last_modep = 0;
        if (in_rdram(modep) && modep != s_last_modep) {
            osViSetMode(rdram, (int32_t)modep);
            s_last_modep = modep;
        }
        if (in_rdram(buf))   osViSwapBuffer(rdram, (int32_t)buf);
    }
}

extern "C" void lambo_thread_trace_dump(int vi); // THROWAWAY diag (mesgqueue.cpp), gated by LAMBO_THREAD_TRACE
static void vi_cb() {
    promote_vi_context();
    const int n = lambo::harness::sample_vi();
    if ((n % 50) == 0) lambo_thread_trace_dump(n); // THROWAWAY: per-thread recv/send snapshot to find the frozen thread
    if (lambo::replay_runtime::should_exit()) {
        const lambo::replay_runtime::Status replay = lambo::replay_runtime::status();
        const std::string reason = lambo::replay_runtime::terminal_reason();
        harness_summary_and_exit(reason.empty() ? "replay_failed" : reason.c_str(),
                                 replay.failed ? 3 : 0);
    }
    if (n == kQuitAfterVis) {
        LAMBO_LOG("probe", "reached %d VIs; quitting\n", n);
        boot_summary_and_exit();
    }
}

// Audio RSP ucode (M_AUDTASK = task type 2, aspMain). librecomp ships no audio ucode and a real
// recompiled aspMain is a large standalone effort -- the faithful end state, tracked under the AUDIO
// epic #53 (this no-op is the scaffold to retire when real aspMain lands). #58 is the descent-crash
// epic this boundary belongs to.
// SCAFFOLD: this no-op ucode signals RspExitReason::Broke so run_task() succeeds (rsp.cpp:55) and the
// audio thread proceeds. It synthesises NO PCM, so it does NOT fill (or zero) the audio DMA buffer:
// osAiSetNextBuffer (routed to the native, gen_syms_toml.py) queues whatever stale RDRAM sits in that
// buffer into ultramodern's audio backend. That is inaudible TODAY only because the headless build has
// no audio sink; once a real output device is driven, audio_ucode_noop must be replaced by real aspMain
// (or made to zero the buffer) to avoid emitting garbage -- it is NOT a silence guarantee. The point of
// the scaffold is purely to clear the CRASH boundary: the native route runs the submit path WITHOUT the
// raw AI-MMIO poll that used to SIGSEGV in __osAiDeviceBusy (func_80080950). Same scaffold class as the
// no-op __osViInit/osCreatePiManager. Gfx tasks (type 1) never reach here -- intercepted by the renderer.
static RspExitReason audio_ucode_noop(uint8_t* /*rdram*/, uint32_t /*ucode_addr*/) {
    static std::atomic<bool> logged{false};
    if (!logged.exchange(true))
        LAMBO_LOG("probe", "audio_ucode_noop: first M_AUDTASK (type 2) -> Broke (no PCM; #53)\n");
    return RspExitReason::Broke;
}

// RSPRecomp'd audio microcode (W135, 2026-07-04, #53): generated from the ROM's aspMain text at
// ROM 0x88B90 (see recomp/aspMain.us.toml for the ground-truth derivation + regen command). This
// RETIRES the audio_ucode_noop scaffold above for the M_AUDTASK path: librecomp's run_task loads
// the OSTask + ucode data into DMEM and this function synthesises real PCM into the game's audio
// buffers, which osAiSetNextBuffer then queues into the SDL sink.
RspExitReason aspMain(uint8_t* rdram, uint32_t ucode_addr);

static RspUcodeFunc* get_rsp_microcode_stub(const OSTask* task) {
    if (task->t.type == 2) return aspMain; // M_AUDTASK: RSPRecomp'd real synthesis (#53)
    static std::atomic<bool> logged{false};
    if (!logged.exchange(true))
        LAMBO_LOG("probe", "get_rsp_microcode: unhandled task type %u -> nullptr\n",
                     (unsigned)task->t.type);
    return nullptr;
}

static void message_box_stub(const char* msg) {
    LAMBO_LOG("probe", "message_box: %s\n", msg);
}

// Input (#68) — defined below in the input section; used by the window/pump callbacks above them.
static void input_sample();
static void rumble_apply();  // rumble-pak sink (#69); defined in the input section below
static std::unique_ptr<lambo::controls::SdlAdapter> g_controls;

// The SDL window, kept for main-thread window ops (fullscreen toggle). SDL window
// state is owned by THIS thread; the renderer only ever sees the raw handle.
static SDL_Window* g_sdl_window = nullptr;
static lambo::StartupController* g_startup_controller = nullptr;

// F11 / Alt+Enter fullscreen toggle (main thread, called from the SDL event loop).
// SDL owns the window state; the new mode is persisted to graphics.json so the next
// launch starts in the same mode. Two deliberate omissions:
//  - rt64_renderer.cpp's update_config setFullScreen path is not used (one owner);
//  - ultramodern::renderer::set_graphics_config is NOT called here: it would be the
//    only mid-game config writer, racing the gfx thread's UNLOCKED config copy
//    (get_graphics_config returns a reference whose guard is released on return --
//    an upstream ultramodern flaw). Nothing renderer-side consumes wm_option, so the
//    live config staying at its startup value is harmless.
static void toggle_fullscreen() {
    lambo::menu::toggle_fullscreen();
}

static ultramodern::renderer::WindowHandle create_window_stub(void* /*gfx_data*/) {
    // RT64 default presenter (#58): RT64 needs a real window with a Vulkan surface
    // (Linux). Created on the main thread; the SDL event pump runs in update_gfx_stub
    // below (also main thread, via recomp::start's loop). LAMBO_HEADLESS=1 (harness
    // knob) skips the window entirely; SDL failure degrades to headless the same way.
    if (lambo_rt64::enabled()) {
        // Enable SDL2's native Steam Controller HIDAPI driver (original Steam Controller); newer
        // pads (incl. Steam Controller Gen2 via Steam Input) present as a standard XInput gamepad
        // that the SDL_GameController API handles without this hint. Must precede SDL init.
        SDL_SetHint(SDL_HINT_JOYSTICK_HIDAPI_STEAM, "1");
        // Keep controller events flowing even when the window loses focus (matches the reference
        // ports; otherwise held inputs freeze on alt-tab).
        SDL_SetHint(SDL_HINT_JOYSTICK_ALLOW_BACKGROUND_EVENTS, "1");
        // GAMECONTROLLER pulls in JOYSTICK + enables CONTROLLERDEVICEADDED/REMOVED events (#68).
        if (SDL_InitSubSystem(SDL_INIT_VIDEO | SDL_INIT_GAMECONTROLLER) != 0) {
            LAMBO_LOG("rt64", "SDL_InitSubSystem(VIDEO|GAMECONTROLLER) failed: %s -- staying headless\n",
                         SDL_GetError());
            return ultramodern::renderer::WindowHandle{};
        }
        // Open any controller already connected at launch (ADDED events are also queued, but this
        // covers pads present before the event pump starts).
        if (g_controls != nullptr) g_controls->open_existing();
        uint32_t flags = SDL_WINDOW_RESIZABLE;
#if defined(__linux__)
        flags |= SDL_WINDOW_VULKAN;
#endif
        // Window size + startup fullscreen come from graphics.json (loaded in main()
        // before recomp::start). Fullscreen is owned by SDL on this (main) thread --
        // see the F11 handler in update_gfx_stub.
        const lambo::config::WindowSize win_size = lambo::config::window_size();
        if (ultramodern::renderer::get_graphics_config().wm_option ==
            ultramodern::renderer::WindowMode::Fullscreen) {
            flags |= SDL_WINDOW_FULLSCREEN_DESKTOP;
        }
        SDL_Window* window = SDL_CreateWindow("Automobili Lamborghini",
                                              SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED,
                                              win_size.width, win_size.height, flags);
        if (window == nullptr) {
            LAMBO_LOG("rt64", "SDL_CreateWindow failed: %s -- staying headless\n",
                         SDL_GetError());
            return ultramodern::renderer::WindowHandle{};
        }
        g_sdl_window = window;
        lambo::menu::attach(window);
        lambo::ui::set_window(window);
#if defined(__linux__)
        LAMBO_LOG("rt64", "SDL window created (%dx%d, Vulkan surface)\n",
                     win_size.width, win_size.height);
        return ultramodern::renderer::WindowHandle{window};
#elif defined(_WIN32)
        // Native Windows (#68): ultramodern's WindowHandle is {HWND, thread_id} and RT64
        // drives its D3D12 swapchain off the raw HWND, so unwrap it from the SDL window.
        // Same shape as Zelda64Recomp's Windows path (SDL_SysWMinfo -> info.win.window).
        SDL_SysWMinfo wmInfo;
        SDL_VERSION(&wmInfo.version);
        if (SDL_GetWindowWMInfo(window, &wmInfo) != SDL_TRUE) {
            LAMBO_LOG("rt64", "SDL_GetWindowWMInfo failed: %s -- staying headless\n",
                         SDL_GetError());
            SDL_DestroyWindow(window);
            return ultramodern::renderer::WindowHandle{};
        }
        LAMBO_LOG("rt64", "SDL window created (%dx%d, Win32 HWND -> D3D12)\n",
                     win_size.width, win_size.height);
        return ultramodern::renderer::WindowHandle{wmInfo.info.win.window, GetCurrentThreadId()};
#else
        LAMBO_LOG("rt64", "window handle wiring not implemented on this platform\n");
        SDL_DestroyWindow(window);
        return ultramodern::renderer::WindowHandle{};
#endif
    }
    return ultramodern::renderer::WindowHandle{}; // headless: null handle
}

static void update_gfx_stub(void* /*gfx_data*/) {
    lambo::audio::pump();

    static bool runtime_ready_announced = false;
    if (!runtime_ready_announced && g_startup_controller != nullptr) {
        const bool render_ready = lambo::ui::is_initialized();
        const bool runtime_ready = !lambo_rt64::enabled() || render_ready;
        if (runtime_ready &&
            (g_startup_controller->mode() == lambo::StartupMode::Automatic || render_ready)) {
            runtime_ready_announced = true;
            g_startup_controller->runtime_ready();
            const char* page_env = std::getenv("LAMBO_UI_PAGE");
            if (page_env != nullptr) {
                const std::string page(page_env);
                if (page == "settings") lambo::ui::open_settings();
                else if (page == "controls") lambo::ui::open_controls();
                else if (page == "graphics") lambo::ui::open_graphics();
                else if (page == "enhancements") lambo::ui::open_enhancements();
                else if (page == "haptics") lambo::ui::open_haptics();
                else if (page == "launcher") lambo::ui::open_launcher();
            } else if (g_startup_controller->mode() == lambo::StartupMode::InteractiveLauncher) {
                lambo::ui::open_launcher();
            }
        }
    }

    // Pump SDL events on the main thread so the RT64 window stays responsive under WSLg.
    if (lambo_rt64::enabled()) {
        SDL_Event event;
        while (SDL_PollEvent(&event)) {
            // Quit/window-close is handled before any UI or guest dispatch. In particular,
            // a launcher close before the first VI is a successful application exit, not a
            // failed boot probe.
            if (event.type == SDL_QUIT ||
                (event.type == SDL_WINDOWEVENT && event.window.event == SDL_WINDOWEVENT_CLOSE)) {
                if (g_startup_controller != nullptr) g_startup_controller->request_exit();
                application_exit_success();
            }

            // Hotplug is always consumed, even while the launcher owns input.
            if (event.type == SDL_CONTROLLERDEVICEADDED) {
                if (g_controls != nullptr) g_controls->device_added(event.cdevice.which);
                continue;
            }
            if (event.type == SDL_CONTROLLERDEVICEREMOVED) {
                if (g_controls != nullptr) g_controls->device_removed(event.cdevice.which);
                lambo::ui::handle_event(event);
                continue;
            }

            if (g_controls != nullptr && g_controls->handle_capture_event(event)) continue;
            if (lambo::menu::handle_event(event)) continue;
            if (lambo::ui::handle_event(event)) continue;

            // Once the launcher/overlay captures input, guest and developer shortcuts are
            // suppressed. F11 and Alt+Enter remain application-level shortcuts otherwise.
            const bool settings_shortcut =
                (event.type == SDL_KEYDOWN && !event.key.repeat &&
                 (event.key.keysym.sym == SDLK_ESCAPE || event.key.keysym.sym == SDLK_F1)) ||
                (g_controls != nullptr && g_controls->selected_back_pressed(event));
            if (settings_shortcut &&
                g_startup_controller != nullptr &&
                g_startup_controller->state() == lambo::StartupState::Started &&
                !lambo::ui::is_visible()) {
                lambo::ui::open_settings();
                continue;
            }
            if (event.type == SDL_KEYDOWN && !event.key.repeat &&
                (event.key.keysym.sym == SDLK_F11 ||
                 (event.key.keysym.sym == SDLK_RETURN && (event.key.keysym.mod & KMOD_ALT)))) {
                toggle_fullscreen();
            }
        }
        // Severe GPU-driver advisory posted by renderer setup (issue #109): the affected
        // user sees only a black window, so show it as a modal box. Main thread owns all
        // UI; blocking the pump here is fine -- game threads keep running behind it.
        if (const char* advisory = lambo_gpu_advisory_take_pending()) {
            SDL_ShowSimpleMessageBox(SDL_MESSAGEBOX_WARNING,
                                     "Lamborghini Recomp - outdated graphics driver",
                                     advisory, g_sdl_window);
        }
        // Update the cross-thread capture gate before sampling physical state. The guest reads a
        // neutral snapshot while the UI owns input, plus one neutral frame after release.
        if (g_controls != nullptr) g_controls->process_commands();
        lambo::input_gate::set_ui_capture(lambo::ui::captures_input());
        input_sample();
        // Apply the game thread's latest rumble-pak motor state to the physical pad (#69).
        rumble_apply();
    }
}

// --- input (#68) --------------------------------------------------------------------------
// Real SDL2 keyboard + gamepad -> N64 OSContPad, feeding ultramodern's get_input callback
// (which packs our button mask + float stick into OSContPad via osContGetReadData).
//
// Threading: SDL events pump on the MAIN thread (update_gfx_stub); get_input/poll_input are
// called on the GAME thread (osContStartReadData). So the main thread SAMPLES SDL state into
// one atomic snapshot each frame (input_sample()), and the game thread only READS the
// snapshot -- no cross-thread SDL calls, no lock. Snapshot layout (uint32_t):
//   [15:0] = N64 button mask, [23:16] = stick_x (int8), [31:24] = stick_y (int8).
//
// Port 0 is reported connected UNCONDITIONALLY (input_device_info below) even with no physical
// pad: the keyboard is a valid input device, and the ROM's object-slot gate (func_8007A8A0)
// bails to a stuck state 6 unless port 0 reads as present (#64/#53).
//
// LAMBO_MODERN_INPUT (env, hex OS_CONT mask) is OR'd into every read -- the permanent harness
// knob for headless title-advance scripting (LAMBO_HEADLESS never inits SDL gamecontroller, so
// its snapshot stays 0 and get_input returns exactly the env mask, as before this change).

// N64 OSContPad button bits (libultra ultra64/controller.h; standard across all N64 titles).
enum {
    N64_A       = 0x8000, N64_B      = 0x4000, N64_Z     = 0x2000, N64_START = 0x1000,
    N64_DU      = 0x0800, N64_DD     = 0x0400, N64_DL    = 0x0200, N64_DR    = 0x0100,
    N64_L       = 0x0020, N64_R      = 0x0010,
    N64_CU      = 0x0008, N64_CD     = 0x0004, N64_CL    = 0x0002, N64_CR    = 0x0001,
};

// N64 hardware stick maxes at roughly +-80 after calibration; games are tuned for that range,
// so we scale full deflection to +-80 (faithfulness) rather than the full int8 +-127.
static constexpr int   N64_STICK_MAX   = 80;
static uint16_t g_held_buttons = 0;                 // LAMBO_MODERN_INPUT env override, OR'd in
static int8_t   g_held_sx = 0, g_held_sy = 0;       // LAMBO_MODERN_INPUT stick override (harness)
static float    g_held_throttle = -1.0f;             // LAMBO_ANALOG_THROTTLE=[0,1] override
static float    g_held_brake = -1.0f;                // LAMBO_ANALOG_BRAKE=[0,1] override
// LAMBO_INPUT_PULSE=BTNHEX:PERIOD:DUTY[:STARTVI] -- periodic button pulse for headless menu
// navigation (a held LAMBO_MODERN_INPUT mask is one EDGE forever, so it can advance at most one
// menu; a pulse presses/releases every PERIOD VIs for DUTY VIs, walking a whole menu chain).
static uint16_t g_pulse_buttons = 0;
static int      g_pulse_period = 0, g_pulse_duty = 0, g_pulse_start = 0;
static int      g_pulse_count = 0;   // optional 5th field: stop after N pulses (0 = unlimited)

// --- rumble-pak sink (#69) ----------------------------------------------------------------
// The game's SI/PIF bridge (func_8007F780 -> lambo_joybus_answer, recomp/src/libultra_stubs.c)
// runs on the GAME thread and decodes the ROM's motor-control pak writes (joybus cmd 0x03 to
// pak block 0xC000: payload 0x01 = motor on, 0x00 = off). SDL rumble must be driven from the
// MAIN thread (that owns the controller registry), so -- exactly like input -- the game thread only
// PUBLISHES an atomic request and the main-thread pump (update_gfx_stub) applies it. Declared
// extern "C" so the C responder in libultra_stubs.c can call lambo_pak_set_rumble().
static std::atomic<int> g_rumble_on{0};              // game-thread write, main-thread read
extern "C" void lambo_pak_set_rumble(int on) { g_rumble_on.store(on ? 1 : 0, std::memory_order_relaxed); }

// Developer warp menu (#12, src/lambo_warp.c): main thread publishes, game thread warps.
extern "C" void lambo_warp_request(int circuit0);

// Developer save-state (#22, src/lambo_savestate.c): F7 snapshots guest RAM, F8 restores it.
// Main thread flips the request bit; the game thread does the copy at the next frame boundary.
extern "C" void lambo_savestate_request_save(void);
extern "C" void lambo_savestate_request_load(void);

// Apply the published rumble state to the physical pad. Called once per main-thread pump.
// N64 rumble is bang-bang (motor fully on or off), so map to SDL full strength. We refresh the
// effect every pump with a short expiry (150 ms > one 30 fps frame) so a sustained motor-on
// keeps buzzing without needing a re-trigger, and a single motor-off (or a dropped controller)
// lets it lapse. Idempotent-ish: we only issue an SDL call on an on/off EDGE plus periodic
// refresh while on, to avoid hammering the HID layer every frame.
static void rumble_apply() {
    int on = g_rumble_on.load(std::memory_order_relaxed);
    if (g_controls != nullptr) g_controls->apply_rumble(on != 0);
}

// Sample SDL keyboard + gamepad on the MAIN thread and publish the atomic snapshot.
static void input_sample() {
    uint16_t b = 0;
    int sx = 0, sy = 0;
    lambo::controls::EvaluatedState controller{};

    if (g_controls != nullptr) {
        controller = g_controls->sample();
        b = controller.buttons;
        sx = controller.stick_x;
        sy = controller.stick_y;
    }

    // Keyboard fallback (always sampled; OR'd with the pad). Arrow keys steer; racing essentials
    // on the left hand. Digital keys drive the stick to full deflection only if the pad is idle.
    if (const Uint8* ks = SDL_GetKeyboardState(nullptr)) {
        if (ks[SDL_SCANCODE_X])      b |= N64_A;       // accelerate / confirm
        if (ks[SDL_SCANCODE_C])      b |= N64_B;       // brake / cancel
        if (ks[SDL_SCANCODE_Z])      b |= N64_Z;
        if (ks[SDL_SCANCODE_RETURN]) b |= N64_START;
        if (ks[SDL_SCANCODE_Q])      b |= N64_L;
        if (ks[SDL_SCANCODE_E])      b |= N64_R;
        if (ks[SDL_SCANCODE_I])      b |= N64_CU;
        if (ks[SDL_SCANCODE_K])      b |= N64_CD;
        if (ks[SDL_SCANCODE_J])      b |= N64_CL;
        if (ks[SDL_SCANCODE_L])      b |= N64_CR;
        int kx = 0, ky = 0;
        if (ks[SDL_SCANCODE_LEFT]  || ks[SDL_SCANCODE_A]) kx -= N64_STICK_MAX;
        if (ks[SDL_SCANCODE_RIGHT] || ks[SDL_SCANCODE_D]) kx += N64_STICK_MAX;
        if (ks[SDL_SCANCODE_UP]    || ks[SDL_SCANCODE_W]) ky += N64_STICK_MAX;
        if (ks[SDL_SCANCODE_DOWN]  || ks[SDL_SCANCODE_S]) ky -= N64_STICK_MAX;
        if (sx == 0 && kx != 0) sx = kx;               // pad stick wins if deflected
        if (sy == 0 && ky != 0) sy = ky;

        if (!lambo::input_gate::guest_input_suppressed()) {
            // Developer warp menu (#12): F1..F6 warp straight to that circuit as a
            // 1-player single race. Edge-detected here (main thread); consumed by
            // lambo_warp_tick on the game thread (src/lambo_warp.c).
            static Uint8 warp_prev[6] = {};
            for (int i = 0; i < 6; i++) {
                Uint8 down = ks[SDL_SCANCODE_F1 + i];
                if (down && !warp_prev[i]) lambo_warp_request(i);
                warp_prev[i] = down;
            }

            // Developer save-state (#22): F7 saves the current guest RAM to the state slot,
            // F8 restores it. Edge-detected here (main thread); the copy runs on the game
            // thread at the next frame boundary (src/lambo_savestate.c).
            static Uint8 f7_prev = 0, f8_prev = 0;
            Uint8 f7 = ks[SDL_SCANCODE_F7], f8 = ks[SDL_SCANCODE_F8];
            if (f7 && !f7_prev) lambo_savestate_request_save();
            if (f8 && !f8_prev) lambo_savestate_request_load();
            f7_prev = f7; f8_prev = f8;
        }
    }

    const bool forced_analog = g_held_throttle >= 0.0f;
    const bool analog_mode = forced_analog ||
        controller.throttle_mode == lambo::controls::ThrottleMode::Analog;
    const float physical_throttle = forced_analog ? g_held_throttle : controller.throttle;
    const bool forced_brake = g_held_brake >= 0.0f;
    const bool brake_analog_mode = forced_brake ||
        controller.brake_mode == lambo::controls::BrakeMode::Analog;
    const float physical_brake = forced_brake ? g_held_brake : controller.brake;
    uint32_t snap = (uint16_t)b
                  | ((uint32_t)(uint8_t)(int8_t)sx << 16)
                  | ((uint32_t)(uint8_t)(int8_t)sy << 24);
    // A throttle-only source must also hold the UI release barrier. The sentinel is
    // observed only while suppression is already active, so it can never reach the ROM.
    const bool suppressed_before_publish = lambo::input_gate::guest_input_suppressed();
    const uint32_t gated_snap = suppressed_before_publish && analog_mode && physical_throttle > 0.0f
        ? (snap | 1u) : snap;
    lambo::input_gate::publish_physical_snapshot(gated_snap);
    const float throttle = lambo::input_gate::guest_input_suppressed()
        ? 0.0f : physical_throttle;
    const float brake = lambo::input_gate::guest_input_suppressed()
        ? 0.0f : physical_brake;
    lambo::replay_runtime::publish_physical_analog(
        analog_mode, throttle, brake_analog_mode, brake);
}

static void input_poll_stub() {}
static bool input_get_input(int controller_num, uint16_t* buttons, float* x, float* y) {
    if (controller_num != 0) return false;
    const bool suppressed = lambo::input_gate::guest_input_suppressed();
    uint32_t snap = lambo::input_gate::guest_snapshot();
    uint16_t b = suppressed ? 0 : (uint16_t)(snap & 0xFFFF);
    if (!suppressed) b |= g_held_buttons;                       // env mask is a guest input source
    if (!suppressed && g_pulse_period > 0) {                    // scripted pulse (harness knob)
        const int vi = lambo::harness::vis_count();
        if (vi >= g_pulse_start && ((vi - g_pulse_start) % g_pulse_period) < g_pulse_duty
            && (g_pulse_count == 0 || (vi - g_pulse_start) / g_pulse_period < g_pulse_count))
            b |= g_pulse_buttons;
    }
    int8_t   sx = (int8_t)((snap >> 16) & 0xFF);
    int8_t   sy = (int8_t)((snap >> 24) & 0xFF);
    if (!suppressed && sx == 0) sx = g_held_sx;                  // env stick fills in when live stick idle
    if (!suppressed && sy == 0) sy = g_held_sy;

    lambo::replay::InputFrame replay_frame{};
    if (lambo::replay_runtime::playback_frame(replay_frame)) {
        b = replay_frame.buttons;
        sx = replay_frame.stick_x;
        sy = replay_frame.stick_y;
    }
    if (buttons) *buttons = b;
    // ultramodern does stick_x = (int8_t)(127 * x), so divide by 127 (NOT N64_STICK_MAX) to
    // preserve our authentic +-80 range through that re-scale instead of re-expanding to +-127.
    if (x) *x = sx / 127.0f;
    if (y) *y = sy / 127.0f;
    return true;
}
static ultramodern::input::connected_device_info_t input_device_info(int controller_num) {
    using namespace ultramodern::input;
    if (controller_num == 0) return { Device::Controller, Pak::None };
    return { Device::None, Pak::None };
}

static bool is_controller_pak_container(const char* path) {
    const char* extension_start = std::strrchr(path, '.');
    const char* forward_slash = std::strrchr(path, '/');
    const char* back_slash = std::strrchr(path, '\\');
    const char* slash = forward_slash == nullptr ? back_slash :
        (back_slash == nullptr || forward_slash > back_slash ? forward_slash : back_slash);
    if (extension_start == nullptr || (slash != nullptr && extension_start < slash)) return false;
    std::string extension = extension_start;
    std::transform(extension.begin(), extension.end(), extension.begin(),
                   [](unsigned char ch) { return static_cast<char>(std::tolower(ch)); });
    if (extension != ".mpk" && extension != ".pak" &&
        extension != ".srm" && extension != ".n64") return false;
    const LamboPakIoResult result = lambo_pak_probe_file(path);
    if (!result.ok) return false;
    switch (result.format) {
    case LAMBO_PAK_FORMAT_RAW:
    case LAMBO_PAK_FORMAT_FOUR_PORT:
        return extension == ".mpk" || extension == ".pak";
    case LAMBO_PAK_FORMAT_RETROARCH:
        return extension == ".srm";
    case LAMBO_PAK_FORMAT_DEXDRIVE:
        return extension == ".n64";
    default:
        return false;
    }
}

static std::string path_to_utf8(const std::filesystem::path& path) {
    const std::u8string value = path.u8string();
    return {reinterpret_cast<const char*>(value.data()), value.size()};
}

static std::filesystem::path path_from_utf8(const char* path) {
    const auto* begin = reinterpret_cast<const char8_t*>(path);
    return std::filesystem::path(std::u8string(begin, begin + std::strlen(path)));
}

static std::filesystem::path unused_backup_path(const std::filesystem::path& path) {
    std::filesystem::path candidate = path;
    candidate += ".bak";
    for (unsigned index = 1; std::filesystem::exists(candidate); ++index) {
        candidate = path;
        candidate += ".bak." + std::to_string(index);
    }
    return candidate;
}

static int application_main(int argc, char** argv) {
    // Parse and initialise logging before any startup path can emit a message.
    // The Windows target is GUI-subsystem, so --console is responsible for
    // attaching/allocating the live stderr sink.
    if (!lambo_log_parse_args(argc, argv)) {
        (void)lambo_log_initialize();
        // Command-line syntax errors must remain visible even when the user
        // did not request a console or the log directory is unavailable.
        std::fprintf(stderr, "[error] [log] %s\n", lambo_log_last_error());
        return 2;
    }
    (void)lambo_log_initialize();
#if defined(_WIN32)
    // SDL2main normally performs this when it owns WinMain. This target owns
    // WinMain because it is a GUI-subsystem executable.
    SDL_SetMainReady();
#endif
    // Deterministic lighting self-test: no ROM, no runtime -- exercises the swrender
    // light-decode + lambert path on a synthetic DL and exits (tests/pivot/test_lighting.py).
    if (std::getenv("LAMBO_LIGHTING_SELFTEST")) {
        return headless::run_lighting_selftest();
    }
    const char* rom_path = "Automobili Lamborghini (USA).z64";
    const char* import_path = nullptr;
    const char* controller_pak_path = nullptr;
    bool rom_was_selected = false;
    for (int i = 1; i < argc; ++i) {
        if (argv[i] && std::strcmp(argv[i], "--import-save") == 0) {
            if (i + 1 >= argc || argv[i + 1] == nullptr || argv[i + 1][0] == '\0') {
                std::fprintf(stderr,
                             "[error] [cli] --import-save requires an MPK, SRM, or DexDrive N64 file\n");
                return 2;
            }
            import_path = argv[++i];
        } else if (argv[i] && std::strcmp(argv[i], "--controller-pak") == 0) {
            if (i + 1 >= argc || argv[i + 1] == nullptr || argv[i + 1][0] == '\0') {
                std::fprintf(stderr,
                             "[error] [cli] --controller-pak requires an MPK, SRM, or DexDrive N64 file\n");
                return 2;
            }
            controller_pak_path = argv[++i];
        } else if (argv[i] && std::strcmp(argv[i], "--log-level") == 0) {
            // lambo_log_parse_args already validated and consumed this value;
            // keep the ROM selector from mistaking it for a ROM path.
            ++i;
        } else if (argv[i] && argv[i][0] != '-' && argv[i][0] != '\0' &&
                   is_controller_pak_container(argv[i])) {
            import_path = argv[i];
        } else if (!rom_was_selected && argv[i] && argv[i][0] != '-' && argv[i][0] != '\0') {
            rom_path = argv[i];
            rom_was_selected = true;
        } else if (argv[i] && argv[i][0] == '-') {
            // Logging and future switches are parsed by their owning subsystem;
            // they must never be mistaken for a ROM or save path here.
        }
    }
    LAMBO_LOG("probe", "ROM: %s\n", rom_path);

    register_overlays();
    // After register_overlays so the native-ptr -> vram map is already wired.
    lambo::crash::install();

    // Smoke-test the handler: LAMBO_CRASH_TEST=<reason> schedules a 2 s
    // sleep then a deliberate crash so the dump format can be verified in
    // CI / field testing without waiting for a real bug.
    if (const char* ct = std::getenv("LAMBO_CRASH_TEST")) {
        LAMBO_LOG("probe", "LAMBO_CRASH_TEST=%s; injecting deliberate crash in 2s\n", ct);
        std::thread([](const char* reason){
            std::this_thread::sleep_for(std::chrono::seconds(2));
            lambo::crash::record_recent(0x80001CD0u, 0x800024F8u);  // func_800028D0 entry, $ra into menu driver
            lambo::crash::record_recent(0x80000450u, 0);            // BootMain entry
            lambo::crash::crash_dump_and_die(reason);
        }, ct).detach();
    }

    // Load + apply graphics.json BEFORE recomp::start: ultramodern latches the config
    // and the RT64 context constructor reads it via get_graphics_config(). This is the
    // whole user-facing options mechanism (edit the file; F11 toggles fullscreen live).
    lambo::config::load_and_apply_graphics();

    // librecomp's config path is where game SAVES (EEPROM/SRAM/pak) and mod config
    // live -- point it at the same persistent per-user directory as graphics.json.
    // (It was a throwaway temp dir during the headless-probe era, which silently
    // discarded saves on temp cleanup.)
    std::filesystem::path config_dir = lambo::config::app_config_dir();
    std::filesystem::create_directories(config_dir);
    recomp::register_config_path(config_dir);

    const std::filesystem::path pak_path = config_dir / "lambo_controller_pak.mpk";
    const std::string pak_path_string = path_to_utf8(pak_path);
    std::filesystem::path active_pak_path = pak_path;
    if (controller_pak_path != nullptr) {
        active_pak_path = path_from_utf8(controller_pak_path);
    } else {
#if defined(_WIN32)
        if (const wchar_t* environment_path = _wgetenv(L"LAMBO_CONTROLLER_PAK_FILE");
            environment_path != nullptr && environment_path[0] != L'\0')
            active_pak_path = environment_path;
#else
        if (const char* environment_path = std::getenv("LAMBO_CONTROLLER_PAK_FILE");
            environment_path != nullptr && environment_path[0] != '\0')
            active_pak_path = path_from_utf8(environment_path);
#endif
    }
    const std::string active_pak_path_string = path_to_utf8(active_pak_path);
    lambo_pak_storage_configure(active_pak_path_string.c_str());

    if (import_path != nullptr && controller_pak_path != nullptr) {
        LAMBO_LOG_ERROR("cli", "--import-save and --controller-pak cannot be used together\n");
        return 2;
    } else if (import_path != nullptr) {
        std::error_code error;
        const LamboPakIoResult source = lambo_pak_probe_file(import_path);
        if (!source.ok) {
            LAMBO_LOG_ERROR("pak", "import failed: %s\n", source.error);
            return 2;
        }
        const bool source_is_destination =
            std::filesystem::equivalent(path_from_utf8(import_path), pak_path, error);
        if (source_is_destination && !error) {
            LAMBO_LOG_INFO("pak", "selected save is already the active Controller Pak: %s\n",
                           pak_path_string.c_str());
        } else {
            error.clear();
            if (std::filesystem::exists(pak_path)) {
                const auto backup = unused_backup_path(pak_path);
                std::filesystem::copy_file(pak_path, backup, error);
                if (error) {
                    const std::string backup_string = path_to_utf8(backup);
                    LAMBO_LOG_ERROR("pak", "cannot back up existing save to %s: %s\n",
                                     backup_string.c_str(), error.message().c_str());
                    return 2;
                }
                const std::string backup_string = path_to_utf8(backup);
                LAMBO_LOG_INFO("pak", "backed up existing save to %s\n", backup_string.c_str());
            }
            const LamboPakIoResult imported = lambo_pak_import_file(import_path, pak_path_string.c_str());
            if (!imported.ok) {
                LAMBO_LOG_ERROR("pak", "import failed: %s\n", imported.error);
                return 2;
            }
            LAMBO_LOG_INFO("pak", "imported %s to %s\n",
                           lambo_pak_format_name(imported.format), pak_path_string.c_str());
        }
    } else if (controller_pak_path == nullptr && !std::filesystem::exists(pak_path)) {
        // One-time migration for builds before #176, which accidentally stored the
        // default Controller Pak beside the executable/current working directory.
        const std::filesystem::path legacy = "lambo_controller_pak.mpk";
        if (std::filesystem::exists(legacy)) {
            const std::string legacy_string = path_to_utf8(legacy);
            const LamboPakIoResult migrated =
                lambo_pak_import_file(legacy_string.c_str(), pak_path_string.c_str());
            if (migrated.ok)
                LAMBO_LOG_INFO("pak", "migrated legacy %s save to %s\n",
                               lambo_pak_format_name(migrated.format), pak_path_string.c_str());
            else
                LAMBO_LOG_WARN("pak", "legacy save migration failed: %s\n", migrated.error);
        }
    }
    g_controls = std::make_unique<lambo::controls::SdlAdapter>();

    recomp::GameEntry game{};
    game.rom_hash          = 0x525201d7279f34e3ULL; // XXH3_64(big-endian .z64, padded to /4)
    game.internal_name     = "LAMBORGHINI         "; // ROM header name @0x20 (20 bytes)
    game.game_id           = u8"lamborghini.us";
    game.is_enabled        = true;
    game.entrypoint_address = (gpr)(int32_t)0x80000400u;
    game.entrypoint        = recomp_entrypoint;
    game.on_init_callback  = on_init_cb;
    game.thread_create_callback = thread_create_cb;
    recomp::register_game(game);

    std::u8string game_id = u8"lamborghini.us";
    recomp::RomValidationError verr = recomp::select_rom(rom_path, game_id);
    if (verr != recomp::RomValidationError::Good) {
        LAMBO_LOG_ERROR("rom", "select_rom FAILED (RomValidationError=%d)\n", (int)verr);
        return 1;
    }
    LAMBO_LOG("probe", "ROM validated; rom_hash matches\n");

    if (!lambo::replay_runtime::initialize_from_environment()) {
        const std::string error = lambo::replay_runtime::last_error();
        LAMBO_LOG_ERROR("replay", "cannot initialize input record/replay: %s\n", error.c_str());
        lambo::replay_runtime::finalize();
        const std::string reason = lambo::replay_runtime::terminal_reason();
        const lambo::harness::Outcome outcome = lambo::harness::finalize_outcome(
            reason.empty() ? "invalid_configuration" : reason.c_str(), 2);
        lambo::harness::write_result(outcome);
        (void)lambo_pak_storage_flush();
        lambo_log_shutdown();
        return 2;
    }

    lambo::StartupMode startup_mode = lambo::startup_mode_from_environment();
    if (startup_mode == lambo::StartupMode::Automatic && lambo::config::show_launcher()) {
        startup_mode = lambo::StartupMode::InteractiveLauncher;
    }
    lambo::StartupController startup_controller(startup_mode, []() {
        LAMBO_LOG("probe", "calling start_game\n");
        recomp::start_game(u8"lamborghini.us");
    });
    g_startup_controller = &startup_controller;
    lambo::ui::set_startup_controller(&startup_controller);
    lambo::ui::install_render_hooks();
    LAMBO_LOG_INFO("startup", "startup mode: %s\n",
              startup_mode == lambo::StartupMode::Automatic ? "automatic" : "interactive");

    // Watchdog: guarantee automatic probes terminate and report. Only started for
    // capped test probes (kQuitAfterVis != INT_MAX). Normal play mode runs unwatched.
    if (kQuitAfterVis != INT_MAX) {
        const int wd_sec = watchdog_seconds();
        std::thread watchdog([&startup_controller, wd_sec]() {
            while (!startup_controller.watchdog_armed() &&
                   startup_controller.state() != lambo::StartupState::Exiting) {
                std::this_thread::sleep_for(std::chrono::milliseconds(20));
            }
            if (startup_controller.state() == lambo::StartupState::Exiting) return;
            std::this_thread::sleep_for(std::chrono::seconds(wd_sec));
            if (startup_controller.state() == lambo::StartupState::Exiting) return;
            const lambo::harness::Snapshot metrics = lambo::harness::snapshot();
            LAMBO_LOG("probe", "WATCHDOG %ds: threads=%d vis=%d first_vi=%d\n",
                      wd_sec, metrics.threads, metrics.vis, static_cast<int>(metrics.first_vi));
            // Exit deterministically (same as the VI-cap path) rather than ultramodern::quit(),
            // whose teardown munmaps RDRAM out from under the live game threads (SIGSEGV race).
            harness_summary_and_exit("watchdog", 2);
        });
        watchdog.detach();
    }

    recomp::Configuration cfg{};
    cfg.project_version = recomp::Version{
        LAMBO_VERSION_MAJOR, LAMBO_VERSION_MINOR, LAMBO_VERSION_PATCH, std::string{}};
    cfg.rsp_callbacks.get_rsp_microcode = get_rsp_microcode_stub;
    cfg.renderer_callbacks.create_render_context = headless::create_render_context;
    cfg.gfx_callbacks.create_window = create_window_stub; // avoids start()'s no-window assert
    cfg.gfx_callbacks.update_gfx = update_gfx_stub;       // SDL event pump when RT64 is active
    cfg.events_callbacks.vi_callback = vi_cb;
    cfg.error_handling_callbacks.message_box = message_box_stub;
    // window_handle left default-empty -> create_window_stub() is used.

    // Controller 0 is wired by DEFAULT (#64/#53, 2026-06-29): the ROM's controller subsystem
    // gates object-slot registration on a clean controller status, and ares boots with 4 detected
    // controllers (count D_8011C681=4). With NO controller wired the read returns "no response"
    // and the object-slot gate func_8007A8A0 (via func_80083100) bails -> stuck at state 6.
    // LAMBO_MODERN_INPUT still overrides the held-button mask for input testing (e.g. =1000 holds
    // START); default (unset) = controller 0 connected, no buttons held.
    if (const char* in = std::getenv("LAMBO_MODERN_INPUT")) {
        // Format: BTNHEX[:SX[:SY]]. OS_CONT bits: START=0x1000, A=0x8000, B=0x4000; SX/SY are
        // signed decimal stick values. e.g. LAMBO_MODERN_INPUT=1000 holds START;
        // LAMBO_MODERN_INPUT=0:53:0 holds the stick at x=+53 with no buttons.
        char* end = nullptr;
        g_held_buttons = (uint16_t)std::strtoul(in, &end, 16);
        if (end != nullptr && *end == ':') {
            g_held_sx = (int8_t)std::strtol(end + 1, &end, 10);
            if (end != nullptr && *end == ':') {
                g_held_sy = (int8_t)std::strtol(end + 1, nullptr, 10);
            }
        }
    }
    if (const char* analog = std::getenv("LAMBO_ANALOG_THROTTLE")) {
        char* end = nullptr;
        const float parsed = std::strtof(analog, &end);
        if (end != analog && end != nullptr && *end == '\0' && std::isfinite(parsed)) {
            g_held_throttle = std::clamp(parsed, 0.0f, 1.0f);
            // Headless mode has no SDL event pump, so publish the deterministic
            // harness value here as well as from input_sample's normal main-thread path.
            lambo::analog_throttle::publish(0, true, g_held_throttle);
            LAMBO_LOG("probe", "analog throttle override: %.3f\n", g_held_throttle);
        }
    }
    lambo::analog_throttle::set_probe(std::getenv("LAMBO_ANALOG_THROTTLE_PROBE") != nullptr);
    if (const char* analog = std::getenv("LAMBO_ANALOG_BRAKE")) {
        char* end = nullptr;
        const float parsed = std::strtof(analog, &end);
        if (end != analog && end != nullptr && *end == '\0' && std::isfinite(parsed)) {
            g_held_brake = std::clamp(parsed, 0.0f, 1.0f);
            // Headless mode has no SDL event pump, so publish the deterministic
            // harness value here as well as from input_sample's normal main-thread path.
            lambo::analog_brake::publish(0, true, g_held_brake);
            LAMBO_LOG("probe", "analog brake override: %.3f\n", g_held_brake);
        }
    }
    lambo::analog_brake::set_probe(std::getenv("LAMBO_ANALOG_BRAKE_PROBE") != nullptr);
    if (const char* pu = std::getenv("LAMBO_INPUT_PULSE")) {
        // BTNHEX:PERIOD:DUTY[:STARTVI[:COUNT]], VI units. e.g. 1000:150:4:300 taps START for 4 VIs
        // every 150 VIs starting at VI 300 -- enough edges to walk the whole menu chain headless.
        // COUNT stops after N taps (0/absent = unlimited) so a walk can PARK on a target screen.
        char* end = nullptr;
        g_pulse_buttons = (uint16_t)std::strtoul(pu, &end, 16);
        if (end && *end == ':') g_pulse_period = (int)std::strtol(end + 1, &end, 10);
        if (end && *end == ':') g_pulse_duty   = (int)std::strtol(end + 1, &end, 10);
        if (end && *end == ':') g_pulse_start  = (int)std::strtol(end + 1, &end, 10);
        if (end && *end == ':') g_pulse_count  = (int)std::strtol(end + 1, nullptr, 10);
        LAMBO_LOG("probe", "input pulse: btn=%04x period=%d duty=%d start=%d count=%d\n",
                     g_pulse_buttons, g_pulse_period, g_pulse_duty, g_pulse_start, g_pulse_count);
    }
    cfg.input_callbacks.poll_input = input_poll_stub;
    cfg.input_callbacks.get_input = input_get_input;
    cfg.input_callbacks.get_connected_device_info = input_device_info;
    LAMBO_LOG("probe", "input: controller0 connected (default), buttons=%04x\n", g_held_buttons);

    // Audio epic #53 (PR 1 of 3): initialize the host audio sink. ultramodern
    // reads cfg.audio_callbacks inside recomp::start (recomp.cpp:743), before
    // preinit (recomp.cpp:809) calls init_audio() -> set_audio_frequency(48000).
    // init() makes the initial main-thread attempt; update_gfx_stub() pumps
    // later discovery/recovery before the per-game AI buffers are submitted.
    // The per-game osAiSetNextBuffer_recomp calls later
    // (recomp/funcs_8.c lines 2186, 2828, 3755, 3764, 4075) route the AI buffer
    // into SDL via ultramodern's shim.
    lambo::audio::init(48000);
    lambo::audio::get_callbacks(&cfg.audio_callbacks);
    LAMBO_LOG("probe", "audio: callbacks wired (queue_samples/get_frames_remaining/set_frequency)\n");

    LAMBO_LOG("probe", "calling recomp::start\n");
    recomp::start(cfg);
    // Reached only via the watchdog quit path (a boot stall before the VI cap): the VI-cap
    // path exits from vi_cb via boot_summary_and_exit() and never returns here.
    harness_summary_and_exit("runtime_return", lambo::harness::snapshot().first_vi ? 0 : 2);
}

#if defined(_WIN32)
static int windows_command_line_main() {
    int argument_count = 0;
    wchar_t** wide_arguments = CommandLineToArgvW(GetCommandLineW(), &argument_count);
    if (wide_arguments == nullptr) return 2;
    std::vector<std::string> arguments;
    std::vector<char*> argument_pointers;
    arguments.reserve(static_cast<size_t>(argument_count));
    argument_pointers.reserve(static_cast<size_t>(argument_count) + 1);
    for (int index = 0; index < argument_count; ++index) {
        const int size = WideCharToMultiByte(CP_UTF8, WC_ERR_INVALID_CHARS, wide_arguments[index],
                                             -1, nullptr, 0, nullptr, nullptr);
        if (size == 0) {
            LocalFree(wide_arguments);
            return 2;
        }
        std::string converted(static_cast<size_t>(size), '\0');
        WideCharToMultiByte(CP_UTF8, WC_ERR_INVALID_CHARS, wide_arguments[index], -1,
                            converted.data(), size, nullptr, nullptr);
        converted.pop_back();
        arguments.push_back(std::move(converted));
    }
    LocalFree(wide_arguments);
    for (std::string& argument : arguments) argument_pointers.push_back(argument.data());
    argument_pointers.push_back(nullptr);
    return application_main(argument_count, argument_pointers.data());
}

// The release executable uses the GUI subsystem so Explorer launches do not
// create a console.  Keep argument parsing in one place and let application
// logging decide whether --console needs to allocate a window.
int WINAPI WinMain(HINSTANCE, HINSTANCE, LPSTR, int) {
    return windows_command_line_main();
}
#else
int main(int argc, char** argv) {
    return application_main(argc, argv);
}
#endif
